### ISSUE TITLE
Resolve the proper dust model and naming

### ISSUE THREAD

**Issue by cwwalter** [lsst/sims_photUtils#54]
During work by me, @jchiang87, and @danielsf when we were trying to resolve some issues with PhoSim's extinction model we determined that although the dust model in sims_photUtils was named CCM, it was actually calling a dust model by O’Donnell.  This is a reminder to make sure this is all finally resolved properly if it hasn't been already.

**Comment by rhiannonlynne** [comment]
There are now two methods, setupCCMab and setupODonnellab.
